version: "3.9"

services:
  app:
    container_name: boilerplate_user_service
    image: node:20.13
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      APP_ENV: local
      DATABASE_URL: mysql://root:password@host.docker.internal:3402/boilerplate_user_live
      KAFKA_BROKER: boilerplate_kafka:9094
    ports:
      - "5002:3000"
    working_dir: /var/app/current
    volumes:
      - "./:/var/app/current"
    networks:
      - boilerplate_microservices_network

networks:
  boilerplate_microservices_network:
    driver: bridge